/* Qrypto 2016
**
** GNU Lesser General Public License Usage
** This file may be used under the terms of the GNU Lesser
** General Public License version 2.1 or version 3 as published by the Free
** Software Foundation and appearing in the file LICENSE.LGPLv21 and
** LICENSE.LGPLv3 included in the packaging of this file. Please review the
** following information to ensure the GNU Lesser General Public License
** requirements will be met: https://www.gnu.org/licenses/lgpl.html and
** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** Botan 1.11 is licensed under Simplified BSD License
** CryptoPP 5.6.2 is licensed under Boost Software License 1.0
**/
#ifndef QRYPTO_KEYMAKER_H
#define QRYPTO_KEYMAKER_H

#include <QStringList>

namespace Qrypto
{

/**
 * @brief The KeyMaker class conforms to PKCS #5 PBKDF2-HMAC
 * @ref https://tools.ietf.org/html/rfc2898#section-5.2
 */
class KeyMaker
{
    struct Private;
    Private *d;

public:
    enum Algorithm {
        RipeMD_160,
        RipeMD_320,
        Sha1,
        Sha224,
        Sha256,
        Sha384,
        Sha512,
        Sha3_224,
        Sha3_256,
        Sha3_384,
        Sha3_512,
        Tiger,
        Whirlpool,
        UnknownAlgorithm
    };

    static const QStringList AlgorithmNames;

    /**
     * @brief KeyMaker default constructor
     * @param algorithm
     * @param iterationCount
     */
    KeyMaker(Algorithm algorithm = Sha256, uint iterationCount = 500000);

    KeyMaker(const KeyMaker &keyMaker);

    /**
     * @brief KeyMaker
     * @param algorithmName matches AlgorithmNames Caseinsensitively
     * @param iterationCount
     */
    KeyMaker(const QString &algorithmName, uint iterationCount);

    ~KeyMaker();

    KeyMaker &operator=(const KeyMaker &keyMaker);

    /**
     * @brief deriveKey generates internal key
     * @param password should not be null
     * @param keyLength in bytes
     * @param milliseconds minimum time for key derivation
     * @return derived key length, zero on error
     */
    uint deriveKey(const QByteArray &password, uint keyLength = 16, uint milliseconds = 0);

    const uchar *keyData() const;

    uint keyLength() const;

    /**
     * @brief authenticate message using HMAC of current Algorithm with internal key
     * @param messageData
     * @param messageSize in bytes
     * @return digest code or null QByteArray on error
     * @ref https://tools.ietf.org/html/rfc2898#section-7.1
     */
    QByteArray authenticate(const char *messageData, uint messageSize);

    QByteArray authenticate(const QByteArray &message)
    { return authenticate(message.constData(), message.size()); }

    Algorithm algorithm() const;

    void setAlgorithm(Algorithm algorithm);

    QString algorithmName() const;

    /**
     * @brief setAlgorithmName
     * @param algorithmName will be matched Caseinsensitively
     */
    void setAlgorithmName(const QString &algorithmName);

    uint iterationCount() const;

    void setIterationCount(uint iterationCount);

    /**
     * @brief salt will be autogenerated to the hash digest size in deriveKey if it was empty
     * @return
     */
    QByteArray salt() const;

    /**
     * @brief setSalt would be used for decryption
     * @param salt
     */
    void setSalt(const QByteArray &salt);

    void setSalt(const QString &saltHex)
    { setSalt(QByteArray::fromHex(saltHex.toLatin1())); }

};

}

#endif // QRYPTO_KEYMAKER_H
